PARSEMETA:
  META_PATH: 'data/datasets/products/metadata.json.gz'
  TITLES_PATH: 'data/spm/titles.txt'
  SPM_DIR_PATH: 'data/spm'
  SPM_WP_PATH: 'data/spm/spm.vocab'
  CATEGORY_PATH: 'data/datasets/products/category.txt'
  PARSE_DATA_PATH: 'data/datasets/products/products.tsv'
  DOC2VEC_DIR_PATH: 'data/doc2vec'
  USE_COLS: ['asin', 'imUrl', 'title', 'categories']
  USE_CATE: []
  VOCAB_SIZE: 50000
  N_SAMPLE: 8000000
  N_LOG_PRINT: 20000
  DOC_VEC_SIZE: 500
  DOC2CEC_EPOCHS: 50
  N_WORKERS: 16
  WINDOW_SIZE: 3

MAKEDB:
  TRAIN_DIR_PATH: 'data/datasets/products/train'
  TEMP_DIR_PATH: 'data/datasets/products/tmp'
  CHUNK_SIZE: 50000