PARSEMETA:
  META_PATH: 'data/datasets/products/metadata.json.gz'
  TITLES_PATH: 'data/spm/titles.txt'
  SPM_DIR_PATH: 'data/spm'
  SPM_WP_PATH: 'data/spm/spm.vocab'
  CATEGORY_PATH: 'data/datasets/products/category.txt'
  PARSE_DATA_PATH: 'data/datasets/products/products.tsv'
  DOC2VEC_DIR_PATH: 'data/doc2vec'
  USE_COLS: ['asin', 'imUrl', 'title', 'categories']
  USE_CATE: [] #['Musical Instruments'] #['Cell Phones & Accessories']
  CATE_DEPTH: 4
  N_SHUFFLE: 3
  VOCAB_SIZE: 10000
  N_SAMPLE: 10000000
  N_LOG_PRINT: 1000
  DOC_VEC_SIZE: 100
  DOC2CEC_EPOCHS: 40
  N_WORKERS: 4
  WINDOW_SIZE: 3

MAKEDB:
  TRAIN_DIR_PATH: 'data/datasets/products/train'
  TEMP_DIR_PATH: 'data/datasets/products/tmp'
  CHUNK_SIZE: 10000